# EECS545 WN2020 Python Tutorial

Instructors:

- **Sungryull Sohn** <srsohn@umich.edu>
- Yijie Guo <guoyijie@umich.edu>
- GS Oh <gsoh@umich.edu>


Adapted from:
- EECS545 FA2019 Python Tutorial (Part I) by [Jongwook choi](https://wook.kr/)
- CS231n python Tutorial by [Volodymyr Kuleshov](http://ai.stanford.edu/~kuleshov/) and [Isaac Caswell](https://www.linkedin.com/in/isaac-caswell-5b264451),
- the `CS231n` Python tutorial by Justin Johnson (http://cs231n.github.io/python-numpy-tutorial/).
- EECS 545 Fall 2017 & Winter 2018 Python Tutorial
- Python Data Science Handbook (O'Reilly): https://github.com/jakevdp/PythonDataScienceHandbook

# Outline

- **Environment Setup (Installation, Anaconda, Jupyter)** (15 mins)
- **Basics of Python** (20 mins)
- **Numpy** (25 mins)

# Introduction

Python is a great general-purpose programming language on its own, but with the help of a few popular libraries (numpy, scipy) it becomes a powerful environment for scientific computing.

We expect that many of you will have some experience with Python and numpy; for the rest of you, this section will serve as a quick crash course both on the Python programming language and on the use of Python for scientific computing.

Some of you may have previous knowledge in Matlab, in which case we also recommend the numpy for Matlab users page (https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html).

In this tutorial, we will cover:

* Basic Python: Basic data types, Containers, Lists, Dictionaries, Sets, Tuples, Functions, Classes
* Numpy: Arrays, Array indexing, Datatypes, Array math, Broadcasting
* IPython: Creating notebooks, Typical workflows

# Installation

## Anaconda Python 3

In EECS 545, we will be using Python 3 (Python 3.6 or 3.7 is highly recommended).

We in particular recommend you install Anaconda for **Python 3**: https://www.anaconda.com/download/. Anaconda is a distribution of Python that has common libraries for this course pre-installed. You can test your installation and that the appropriate libraries are available by running the line of code below:

In [34]:
import sys
sys.version

'3.6.9 (default, Nov  7 2019, 10:44:02) \n[GCC 8.3.0]'

In [5]:
import numpy as np
np.__version__

'1.17.5'

If you need to install a python package, you can run a `pip install` command. For example:

```
$ pip install pandas
```

In [0]:
import pandas

## Jupyter Notebook

In this tutorial, we will use Jupyter Notebook (Jupyter Lab). The Jupyter Notebook is a powerful tool and workspace for interactively developing your python codes and visualizing the results. In a larger scale project you will have to write in several python code files (`.py`) or modules, but in this tutorial we will mainly work on Jupyter Notebooks.

In particular, we strongly recommend to use **Jupyter Lab**:

```bash
$ pip install jupyter-lab
$ jupyter-lab
```

You can open this notebook file and start from there -- edit code cells and run them. For more detailed user guide, please have a look at some useful resources:

* Documentation: https://jupyterlab.readthedocs.io/en/stable/user/interface.html
* Keyboard Shortcuts: https://towardsdatascience.com/jypyter-notebook-shortcuts-bf0101a98330

#### Useful Keyboard Shortcuts:

- `a`, `b`: Create a new empty cell above/below
- `Ctrl-Enter`: Run the current cell
- `Shift-Enter`: Run the current cell and move to the next cell
- `Shift-Tab`: Show documentation

## Basics of Python

Python is a high-level, dynamically typed multiparadigm programming language. Python code is often said to be almost like pseudocode, since it allows you to express very powerful ideas in very few lines of code while being very readable. As an example, here is an implementation of the classic quicksort algorithm in Python:

In [36]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

quicksort([3,6,8,10,1,2,1])

[1, 1, 2, 3, 6, 8, 10]

### Basic data types

#### Numbers

Integers and floats work as you would expect from other languages:

In [37]:
x = 3
print(x, type(x))

3 <class 'int'>


In [38]:
print(x + 1)   # Addition;
print(x - 1)   # Subtraction;
print(x * 2)   # Multiplication;
print(x ** 2)  # Exponentiation;

4
2
6
9


In [39]:
x += 1
print(x)  # Prints "4"
x *= 2
print(x)  # Prints "8"

4
8


In [40]:
y = 2.5
print(type(y)) # Prints "<type 'float'>"
print(y, y + 1, y * 2, y ** 2) # Prints "2.5 3.5 5.0 6.25"

<class 'float'>
2.5 3.5 5.0 6.25


Note that unlike many languages, Python does not have unary increment (x++) or decrement (x--) operators.

Python also has built-in types for long integers and complex numbers; you can find all of the details in the [documentation](https://docs.python.org/2/library/stdtypes.html#numeric-types-int-float-long-complex).

#### Booleans

Python implements all of the usual operators for Boolean logic, but uses English words rather than symbols (`&&`, `||`, etc.):

In [13]:
t, f = True, False
print(type(t)) # Prints "<type 'bool'>"

<class 'bool'>


Now we let's look at the operations:

In [14]:
print(t and f) # Logical AND;
print(t or f)  # Logical OR;
print(not t)   # Logical NOT;
print(t != f)  # Logical XOR;

False
True
False
True


#### Strings

In [16]:
hello = 'hello'   # String literals can use single quotes
world = "world"   # or double quotes; it does not matter.
print(hello, len(hello))

hello 5


In [41]:
hw = hello + ' ' + world  # String concatenation
print (hw)  # prints "hello world"

hello world


In [42]:
hw12 = '%s %s %d' % (hello, world, 12)  # sprintf style string formatting
print (hw12)  # prints "hello world 12"

hello world 12


String objects have a bunch of useful methods; for example:

In [43]:
s = "hello"
print (s.capitalize())  # Capitalize a string; prints "Hello"
print (s.upper())       # Convert a string to uppercase; prints "HELLO"
print (s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print (s.center(7))     # Center a string, padding with spaces; prints " hello "
print (s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                 # prints "he(ell)(ell)o"
print ('  world '.strip())  # Strip leading and trailing whitespace; prints "world"

print (s.startswith('h'), s.endswith('lo'))   # True, True

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world
True True


You can find a list of all string methods in the [documentation](https://docs.python.org/2/library/stdtypes.html#string-methods).

#### String Formatting

There are mainly 3 ways to do string formatting:

* (0) ~... + str(i) + ...~
* (1) `%` operator
* (2) `.format()`
* (3) f-string  (Python 3.6+)

In [44]:
# (1) % operator
alpha = 0.3
classifier = 'svm'
seed = 100

"%s %s %s" % (alpha, classifier, seed)

'0.3 svm 100'

In [45]:
print(alpha)
print("%.1f" % alpha)
print("%9.1f" % alpha)
print("%09.5f" % alpha)
print('--------------')
print("%f" % (alpha*1e10))  # floating
print("%e" % (alpha*1e10))  # scientific
print("%g" % (alpha*1e10))  # compact

0.3
0.3
      0.3
000.30000
--------------
3000000000.000000
3.000000e+09
3e+09


In [46]:
# .format()
# {'index' : 'format' }
print( "{}, {}, {}".format(alpha, classifier, seed) )
print( "{1}, {2}, {0}".format(alpha, classifier, seed) )  # only 'index'
print( "alpha = {:.3f}".format(alpha) )  # only 'format'

print("alpha={alpha}, classifier={classifier}, seed={seed}".format(
    alpha=alpha, classifier=classifier, seed=seed))

0.3, svm, 100
svm, 100, 0.3
alpha = 0.300
alpha=0.3, classifier=svm, seed=100


In [0]:
# f-string
f'alpha^2 = {alpha ** 2}, classifier={classifier}, seed={seed}'

In [0]:
job = 'myjob_%f_%s_%s' % (alpha, classifier, seed)
job

### Containers

Python includes several built-in container types: lists, dictionaries, sets, and tuples.

#### Lists

A list is the Python equivalent of an array, but is resizeable and can contain elements of different types:

In [47]:
# Syntax: use bracket. [value, value, ...]
xs = [3, 1, 2]   # Create a list 
print (xs, xs[2])
print (xs[-1])     # Negative indices count from the end of the list; prints "2"

[3, 1, 2] 2
2


In [48]:
xs[2] = 'foo'    # Lists can contain elements of different types
print (xs)

[3, 1, 'foo']


In [49]:
xs.append('bar') # Add a new element to the end of the list
print (xs)  

[3, 1, 'foo', 'bar']


In [50]:
x = xs.pop()     # Remove and return the last element of the list
print (x, xs) 

bar [3, 1, 'foo']


In [51]:
len(xs)          # Get length

3

As usual, you can find all the gory details about lists in the [documentation](https://docs.python.org/2/tutorial/datastructures.html#more-on-lists).

#### Slicing

In addition to accessing list elements one at a time, Python provides concise syntax to access sublists; this is known as slicing:

In [52]:
# range is a built-in function that creates a `generator` of integers (Python 3). In python 2, was returning a list.
nums = list(range(5))

# Syntax: use bracket. [start:end:step]
print ("(1)", nums)         # Prints "[0, 1, 2, 3, 4]"
print ("(2)",  nums[2:4])    # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print ("(3)", nums[2:])     # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print ("(4)", nums[:2])     # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print ("(5)", nums[:])      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print ("(6)", nums[:-1])    # Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [8, 9] # Assign a new sublist to a slice
print ("(7)", nums)         # Prints "[0, 1, 8, 9, 4]"
print ("(8)", nums[::-1])   # Reverts a list

(1) [0, 1, 2, 3, 4]
(2) [2, 3]
(3) [2, 3, 4]
(4) [0, 1]
(5) [0, 1, 2, 3, 4]
(6) [0, 1, 2, 3]
(7) [0, 1, 8, 9, 4]
(8) [4, 9, 8, 1, 0]


#### Loops

You can loop over the elements of a list like this:

In [53]:
animals = ['cat', 'dog', 'monkey']
for animal in animals:
    print (animal)

cat
dog
monkey


If you want access to the index of each element within the body of a loop, use the built-in `enumerate` function:

In [54]:
animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print ('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey


`zip()` makes an iterator that aggregates elements from each of the iterables.

In [55]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
z = [9, 10, 11, 12]

for i, j, k in zip(x, y, z):
    print(i, j, k)

1 5 9
2 6 10
3 7 11
4 8 12


#### List comprehensions:

When programming, frequently we want to transform one type of data into another. As a simple example, consider the following code that computes square numbers:

In [56]:
nums = [0, 1, 2, 3, 4]
squares = []
for x in nums:
    squares.append(x ** 2)
print (squares)

[0, 1, 4, 9, 16]


You can make this code simpler using a list comprehension:

In [57]:
nums = [0, 1, 2, 3, 4]
squares = [x ** 2 for x in nums]  # simpler & faster!
print (squares)

[0, 1, 4, 9, 16]


List comprehensions can also contain conditions:

In [21]:
nums = [0, 1, 2, 3, 4]
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print (even_squares)

[0, 4, 16]


#### Tuples

A tuple is an (immutable) ordered list of values. A tuple is in many ways similar to a list; but tuple is safer and can be used with dictionary (will be covered later).

In [58]:
# Syntax: use parantheses. (value, value, ...)
t = (5, 6)       # Create a tuple
print (t)
print (type(t))


(5, 6)
<class 'tuple'>


In [59]:
t[0] = 1  # Error! you cannot change tuple

TypeError: ignored

#### Dictionaries

A dictionary stores (key, value) pairs, similar to a `Map` in Java or an object in Javascript. You can use it like this:

In [60]:
# Syntax: use braces. {key:value, key:value, ...}
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"

cute
True


In [23]:
d = dict(
    cat='cute',
    dog='furry',
)
print(d)

{'cat': 'cute', 'dog': 'furry'}


In [61]:
d['fish'] = 'wet'      # Set an entry in a dictionary
print (d['fish'])      # Prints "wet"

wet


One caveat: what if the key doesn't exist?

In [62]:
print (d['monkey'])  # KeyError: 'monkey' not a key of d

KeyError: ignored

It is very useful to use `.get()` method:

In [63]:
print (d.get('monkey'))
print (d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print (d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"

None
N/A
wet


In [64]:
del d['fish']        # Remove an element from a dictionary
print (d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

N/A


You can find all you need to know about dictionaries in the [documentation](https://docs.python.org/2/library/stdtypes.html#dict).

It is easy to iterate over the keys in a dictionary:

In [65]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print ('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


If you want access to keys and their corresponding values, use the `items` method:

In [66]:
d = {'person': 2, 'cat': 4, 'spider': 8}
for animal, legs in d.items():        # Use .items() for python 3
    print ('A %s has %d legs' % (animal, legs))

A person has 2 legs
A cat has 4 legs
A spider has 8 legs


Dictionary comprehensions: These are similar to list comprehensions, but allow you to easily construct dictionaries. For example:

In [0]:
nums = [0, 1, 2, 3, 4]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print (even_num_to_square)

#### OrderedDict and defaultdict

Two useful dict-like data structures that are often used are `OrderedDict` and `defaultdict`.


`OrderedDict` are just like regular dictionaries but they remember *the order that items were inserted*. 
- When iterating over an ordered dictionary, the items are returned in the order their keys were first added.
- Note that from Python 3.6+ `dict` behaves like OrderedDict by default (but not guaranteed). From Python 3.7, it is guaranteed.

In [0]:
from collections import OrderedDict

d = OrderedDict()
d['Y'] = 1
d['Z'] = 2
d['X'] = 3

assert list(d.keys()) == ['Y', 'Z', 'X']
for k, v in d.items():
    print(k, v)

`defaultdict` works just like regular dictionaries, but when a key is missing a *default factory* function will be called to fill in the default values.

In [67]:
from collections import defaultdict

s = 'mississippi'
d = defaultdict(int)
for k in s:
    d[k] += 1
    
d

defaultdict(int, {'i': 4, 'm': 1, 'p': 2, 's': 4})

In [68]:
# compare to this (ugly):

d = dict()
for k in s:
    if k in d:
        d[k] += 1
    else:
        d[k] = 1
d

{'i': 4, 'm': 1, 'p': 2, 's': 4}

#### Sets

A set is an unordered collection of distinct elements. As a simple example, consider the following:

In [0]:
# syntax: use brace. (but no colon ':')
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"


In [0]:
animals.add('fish')      # Add an element to a set
print('fish' in animals)
print(len(animals))       # Number of elements in a set;

In [69]:
animals.add('cat')       # Adding an element that is already in the set does nothing
print(len(animals))       

animals.remove('cat')    # Remove an element from a set
print(len(animals))

AttributeError: ignored

Loops: Iterating over a set has the same syntax as iterating over a list; however since sets are unordered, you cannot make assumptions about the order in which you visit the elements of the set:

In [0]:
animals = {'cat', 'dog', 'fish'}
animals |= {'bird'}  # Join two sets

for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

Set comprehensions: Like lists and dictionaries, we can easily construct sets using set comprehensions:

In [0]:
from math import sqrt
{int(sqrt(x)) for x in range(30)}

Compare to dict comprehensions:

In [0]:
{int(sqrt(x)): x for x in range(30)}

### Functions

Python functions are defined using the `def` keyword. For example:

In [70]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


We will often define functions to take optional keyword arguments, like this:

In [71]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s' % name.upper())
    else:
        print('Hello, %s!' % name)

hello('Bob')
hello('Fred', loud=True)

Hello, Bob!
HELLO, FRED


### Classes

The syntax for defining classes in Python is straightforward:

In [0]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(loud=True)   # Call an instance method; prints "HELLO, FRED!"

## Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy.

To use Numpy, we first need to import the `numpy` package:

In [0]:
import numpy as np

### Arrays

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [73]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [75]:
b = np.array([[1, 2, 3], [4, 5, 6]])   # Create a rank 2 array
b
print(b.shape)

(2, 3)


In [0]:
print(b[0, 0])   # preferred than b[0][0]
print(b[0, 1])

The two most basic properties of numpy array are `shape` and `dtype`. You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

In [76]:
print(b.shape)
print(b.dtype)

(2, 3)
int64


Numpy also provides many functions to create arrays:

In [28]:
a = np.zeros((2, 2))  # Create an array of all zeros
a

array([[0., 0.],
       [0., 0.]])

In [29]:
b = np.ones((1, 2))   # Create an array of all ones
b

array([[1., 1.]])

In [30]:
c = np.full((2, 2), 7) # Create a constant array
c

array([[7, 7],
       [7, 7]])

In [31]:
d = np.eye(2)        # Create a 2x2 identity matrix
d

array([[1., 0.],
       [0., 1.]])

In [32]:
e = np.random.random((2, 2)) # Create an array filled with random values
e

array([[0.1883434 , 0.39331011],
       [0.48874511, 0.22855958]])

In [33]:
# Generate a vector of 10 integers in ascending order from 0 to 9
np.arange(10, dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Array indexing

Numpy offers several ways to index into arrays.

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [77]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b.shape)  # ?
print(b)

(2, 2)
[[2 3]
 [6 7]]


A slice of an array is a **view into the same data**, so modifying it will modify the original array.

In [78]:
print(a[0, 1])
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])
a

2
77


array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**Integer indexing V.S. slice indexing.** : Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [79]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
row_r2 = a[1:4, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [81]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


Integer array indexing: When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [0]:
a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]])

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

In [0]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [0]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
a

In [0]:
# Create an array of indices
col = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
a[np.arange(4), col]  # Prints "[ 1  6  7 11]"

In [0]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
a

For brevity we have left out a lot of details about numpy array indexing; if you want to know more you should read the documentation.

### Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [82]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[5,6], [7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [83]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [84]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [85]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [0]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
np.sqrt(x)

Note that unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [86]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [87]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [88]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [89]:
x = np.array([[1,2], [3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [0]:
x.T

In [90]:
v = np.array([[1,2,3]])
print(v)
print(v.T)

[[1 2 3]]
[[1]
 [2]
 [3]]


### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [91]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])  # [4 x 3] matrix
v = np.array([1, 0, 1])  # [3]-dim vector
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [92]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [93]:
y = x + vv  # Add x and vv elementwise
y

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [94]:
print(f"x.shape = {x.shape}, v.shape={v.shape}")
y = x + v  # Add v to each row of x using broadcasting
y

x.shape = (4, 3), v.shape=(3,)


array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

---
Recommended: read the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc). Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

---

Here are some applications of broadcasting:

In [95]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

np.reshape(v, (3, 1)) * w

array([[ 4,  5],
       [ 8, 10],
       [12, 15]])

In [96]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

x + v

array([[2, 4, 6],
       [5, 7, 9]])

In [0]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
x * 2

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

### More Useful Operations

In [98]:
# np.transpose
a = np.arange(60).reshape([3, 4, -1])
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [0]:
# np.swapaxes

In [0]:
# np.newaxis

In [0]:
# np.ravel (flatten)

In [0]:
# Transpose BGR -> RGB Image
import scipy.misc
a = scipy.misc.face()

In [0]:
# np.hstack
# np.vstack

a = np.full([2, 2], 1)
b = np.full([2, 3], 2)
c = np.full([2, 5], 3)

#### Self-study example

Let's compute a pairwise Euclidean distance matrix for feature vectors $X \in \mathbb{R}^{n \times d}$:

We want to have a distance matrix $D(i, j) \in \mathbb{R}^{n \times n}$ such that
$$
  D(i, j) = \sqrt{ \sum_k (X[i, k] - X[j, k])^2 }
$$

In [0]:
#!pip install scikit-learn
from sklearn.datasets import load_iris
X, _ = load_iris(return_X_y=True)
X.shape

In [0]:
import numpy as np
def compute_distance(X):
    result = np.zeros([X.shape[0], X.shape[0]])
    
    for i, x in enumerate(X):
        for j, y in enumerate(X):
            result[i, j] = np.sum((x - y)**2) ** 0.5
    return result
            
%time D_slow = compute_distance(X)
D_slow

But we can do it more efficient using broadcasting and vector arithmetic.

Hint: Think about what the value of $X(i) - X^\top(j)$ will be.

In [0]:
def compute_distance_fast(X):
    B = X[:, None, :]                # [150, 1, 4]
    C = np.transpose(B, [1, 0, 2])   # [1, 150, 4]
    return np.sqrt(np.sum((B - C)**2, axis=2))
            
%time D_fast = compute_distance_fast(X)
assert np.allclose(D_slow, D_fast, atol=1e-9)

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete.

Check out:

- The [numpy reference](http://docs.scipy.org/doc/numpy/reference/)
- [Python For Data Science Cheat Sheet for Numpy Basics](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Numpy_Python_Cheat_Sheet.pdf)

to find out much more about numpy.